# For more details about configuring Dependabot, see full documentations here:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  # Configuration for Make
  - package-ecosystem: "Make"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
