# This workflow is designed to automate the update process for various package ecosystems,
# ensuring that dependencies are kept up-to-date with regular checks.
#
# For more details about configuring Dependabot, see full documentations here:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for pip
  - package-ecosystem: "pip"
    directory: "/"   # Search for "requirements.txt" on root directory
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "mitsuki31"

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"   # Search for ".github/workflows" on root directory
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GH Actions"
      include: "scope"
    labels:
      - "chore"
    assignees:
      - "mitsuki31"

  # Configuration for Maven
  - package-ecosystem: "maven"
    directory: "/"   # Search for "pom.xml" on root directory
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Maven"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "mitsuki31"
