# For more details about configuring Dependabot, see full documentations here:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "pip updated"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "mitsuki31"

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions updated"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "mitsuki31"
