name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Categories filter
categories:
  # New Features
  - title: '🚀 Features & Enhancements'
    labels:
      - 'feature'
      - 'enhancement'
  # Bug Fixes
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  # Maintenances Updates
  - title: '🧰 Maintenances'
    labels:
      - 'chore'
      - 'maintenance'
  # Documentations Updates
  - title: '📑 Documentations'
    labels:
      - 'documentation'
      - 'docs'
  # Removed / Deprecated Feature
  - title: '⛔ Removed'
    labels:
      - 'remove'
      - 'deprecate'
  # Dependencies Updates
  - title: '🧩 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
exclude-labels:
  - 'skip-changelog'

# Auto Labeler
autolabeler:
  # Documentation
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs\/.+/'
      - '/updatedocs\/.+/'
  # Bug Fixes
  - label: 'bugfix'
    branch:
      - '/fix\/.+/'
      - '/fixes\/.+/'
  # New Features
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/features\/.+/'

  # Refactor / Enhancements
  - label: 'enhancement'
    branch:
      - '/refactor\/.+/'
      - '/refactors\/.+/'

  - label: 'chore'
    files:
      - '.github/**/*'

  # Changes on Java code
  - label: 'lang:java'
    files:
      - '*.java'
  # Changes on Python code
  - label: 'lang:python'
    files:
      - '*.py'

change-template: '- $TITLE (JM#$NUMBER) - @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's New 👀
  
  $CHANGES
  
  For more details, see the [full changelogs][changelogs].
  
  ## 🚧 Issues
  
  Report any issues or have any suggestions? [Send them to us][new-issue] and help us improve **JMatrix**.
  
  ---
  
  🛡️ [VirusTotal][virustotal] Scan Detections:
  
  - jmatrix-$RESOLVED_VERSION.jar
  - jmatrix-$RESOLVED_VERSION-sources.jar
  
  
  <!-- LINKS -->
  [changelogs]: https://github.com/mitsuki31/jmatrix/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  [new-issue]: https://github.com/mitsuki31/jmatrix/issues/new/choose
  [virustotal]: https://www.virustotal.com
