name: PyLint

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [Ubuntu, Windows]           # Run on Ubuntu and Windows
        python-version: ["3.7", "3.x"]  # Run on Py3.7 and the latest version

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python ${{ matrix.python-version }}
        id: setup-py
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      # Update pip and install the PyLint
      - name: Install dependencies
        if: ${{ steps.setup-py.outputs.cache-hit != true }}
        run: |
          echo "Updating 'pip'..."
          python -m pip install --upgrade pip
          echo "Installing 'pylint'..."
          pip install pylint

      # Analyze the Python code
      - name: Analyzing the code with pylint
        run: |
          echo "Analyzing the Python code..."
          pylint --rcfile=.pylintrc $(git ls-files '*.py')
